import type { ApiKey, Endpoint, PlanConfig, ReplayRecord, RouteRule, WebhookEvent } from './types'

export const planCatalog: PlanConfig[] = [
  {
    name: 'Free',
    price: '$0',
    eventLimit: 1_000,
    replayLimit: 25,
    routeLimit: 2,
    keyLimit: 1,
    retentionDays: 3,
    summary: 'Local testing, launch checklists, and the first production endpoint.',
  },
  {
    name: 'Pro',
    price: '$19',
    eventLimit: 100_000,
    replayLimit: 5_000,
    routeLimit: 25,
    keyLimit: 5,
    retentionDays: 30,
    summary: 'Production webhook visibility for one growing indie SaaS.',
  },
  {
    name: 'Team',
    price: '$49',
    eventLimit: 1_000_000,
    replayLimit: 50_000,
    routeLimit: 100,
    keyLimit: 20,
    retentionDays: 90,
    summary: 'Shared routing, replay review, and higher-volume operations.',
  },
]

export const seedEndpoints: Endpoint[] = [
  {
    id: 'end_stripe_prod',
    name: 'Stripe production',
    sourceSlug: 'stripe',
    targetUrl: 'https://api.acme.dev/webhooks/stripe',
    signingSecret: 'whsec_prod_8921',
    status: 'healthy',
    successRate: 99.2,
    p95Ms: 142,
    eventsToday: 1842,
  },
  {
    id: 'end_github_app',
    name: 'GitHub app events',
    sourceSlug: 'github',
    targetUrl: 'https://api.acme.dev/integrations/github',
    signingSecret: 'ghsec_app_4037',
    status: 'degraded',
    successRate: 94.6,
    p95Ms: 328,
    eventsToday: 412,
  },
  {
    id: 'end_clerk_auth',
    name: 'Clerk auth stream',
    sourceSlug: 'clerk',
    targetUrl: 'https://api.acme.dev/webhooks/auth',
    signingSecret: 'clsec_1180',
    status: 'healthy',
    successRate: 98.8,
    p95Ms: 118,
    eventsToday: 655,
  },
  {
    id: 'end_linear_ops',
    name: 'Linear triage',
    sourceSlug: 'linear',
    targetUrl: 'https://api.acme.dev/webhooks/linear',
    signingSecret: 'linsec_7204',
    status: 'paused',
    successRate: 100,
    p95Ms: 91,
    eventsToday: 38,
  },
]

export const seedEvents: WebhookEvent[] = [
  {
    id: 'evt_9b21',
    endpointId: 'end_stripe_prod',
    source: 'Stripe',
    eventType: 'invoice.paid',
    status: 'delivered',
    receivedAt: '2026-06-14T07:42:31+08:00',
    attempts: 1,
    payloadJson: {
      id: 'in_1Pj8Xy',
      object: 'invoice',
      amount_paid: 12900,
      currency: 'usd',
      customer: 'cus_indie_482',
      subscription: 'sub_pro_284',
      livemode: true,
    },
  },
  {
    id: 'evt_9b12',
    endpointId: 'end_stripe_prod',
    source: 'Stripe',
    eventType: 'checkout.session.completed',
    status: 'failed',
    receivedAt: '2026-06-14T07:39:10+08:00',
    attempts: 3,
    lastError: '500 from downstream billing-worker after 10s timeout',
    payloadJson: {
      id: 'cs_live_921',
      mode: 'subscription',
      amount_total: 4900,
      customer_email: 'marta@example.com',
      metadata: { plan: 'team', workspace_id: 'ws_48' },
    },
  },
  {
    id: 'evt_8ff8',
    endpointId: 'end_github_app',
    source: 'GitHub',
    eventType: 'pull_request.opened',
    status: 'delivered',
    receivedAt: '2026-06-14T07:34:52+08:00',
    attempts: 1,
    payloadJson: {
      action: 'opened',
      repository: { full_name: 'acme/payments-api' },
      pull_request: { number: 418, title: 'Add regional tax webhook fanout' },
      sender: { login: 'jordan' },
    },
  },
  {
    id: 'evt_8f42',
    endpointId: 'end_clerk_auth',
    source: 'Clerk',
    eventType: 'user.created',
    status: 'delivered',
    receivedAt: '2026-06-14T07:31:18+08:00',
    attempts: 1,
    payloadJson: {
      id: 'user_2jN',
      email_addresses: ['pilot@northstar.dev'],
      created_at: 1781393478,
      public_metadata: { source: 'waitlist-import' },
    },
  },
  {
    id: 'evt_8de1',
    endpointId: 'end_stripe_prod',
    source: 'Stripe',
    eventType: 'invoice.payment_failed',
    status: 'pending',
    receivedAt: '2026-06-14T07:27:06+08:00',
    attempts: 2,
    lastError: 'Queued for retry window after 429 rate limit',
    payloadJson: {
      id: 'in_1Pj8A1',
      object: 'invoice',
      amount_due: 1900,
      customer: 'cus_startup_201',
      next_payment_attempt: 1781480606,
    },
  },
  {
    id: 'evt_8a09',
    endpointId: 'end_github_app',
    source: 'GitHub',
    eventType: 'issues.labeled',
    status: 'throttled',
    receivedAt: '2026-06-14T07:15:42+08:00',
    attempts: 4,
    lastError: 'Route guard paused fanout after 240 events/minute burst',
    payloadJson: {
      action: 'labeled',
      issue: { number: 827, title: 'Webhook loop from status sync' },
      label: { name: 'incident' },
      repository: { full_name: 'acme/customer-hub' },
    },
  },
  {
    id: 'evt_8622',
    endpointId: 'end_linear_ops',
    source: 'Linear',
    eventType: 'issue.updated',
    status: 'delivered',
    receivedAt: '2026-06-14T06:56:14+08:00',
    attempts: 1,
    payloadJson: {
      action: 'update',
      issue: { identifier: 'OPS-391', title: 'Rotate webhook signing secret' },
      actor: { name: 'Priya Shah' },
    },
  },
  {
    id: 'evt_8519',
    endpointId: 'end_stripe_prod',
    source: 'Stripe',
    eventType: 'customer.subscription.updated',
    status: 'delivered',
    receivedAt: '2026-06-14T06:49:33+08:00',
    attempts: 1,
    payloadJson: {
      id: 'sub_growth_719',
      customer: 'cus_growth_719',
      status: 'active',
      items: [{ price: { nickname: 'HookPilot Pro' }, quantity: 1 }],
    },
  },
]

export const seedRoutes: RouteRule[] = [
  {
    id: 'route_high_value',
    endpointId: 'end_stripe_prod',
    name: 'High-value revenue alert',
    condition: 'event.type == invoice.paid && amount > 10000',
    destinationUrl: 'https://hooks.slack.com/services/revenue',
    enabled: true,
  },
  {
    id: 'route_incident_loop',
    endpointId: 'end_github_app',
    name: 'Incident label fanout',
    condition: 'label.name == incident',
    destinationUrl: 'https://api.acme.dev/incidents/github',
    enabled: true,
  },
  {
    id: 'route_auth_trial',
    endpointId: 'end_clerk_auth',
    name: 'Trial user enrichment',
    condition: 'event.type == user.created',
    destinationUrl: 'https://api.acme.dev/enrich/signup',
    enabled: false,
  },
]

export const seedApiKeys: ApiKey[] = [
  {
    id: 'key_live_console',
    label: 'Production ingest',
    prefix: 'hp_live_8f2a',
    hashedKey: 'sha256:9714d8d6c2b0a7c0',
    createdAt: '2026-06-08T09:20:00+08:00',
    usageLimit: 100_000,
  },
  {
    id: 'key_ci_smoke',
    label: 'CI smoke tests',
    prefix: 'hp_test_41ac',
    hashedKey: 'sha256:e280db6b8a94f7b9',
    createdAt: '2026-06-01T14:12:00+08:00',
    revokedAt: '2026-06-12T11:02:00+08:00',
    usageLimit: 1_000,
  },
]

export const seedReplays: ReplayRecord[] = [
  {
    id: 'rep_102',
    eventId: 'evt_9b12',
    targetUrl: 'https://staging.acme.dev/webhooks/stripe',
    status: 'success',
    createdAt: '2026-06-14T07:45:22+08:00',
    message: '200 OK in 218ms',
  },
  {
    id: 'rep_101',
    eventId: 'evt_8de1',
    targetUrl: 'https://api.acme.dev/webhooks/stripe',
    status: 'queued',
    createdAt: '2026-06-14T07:29:02+08:00',
    message: 'Waiting for retry budget',
  },
]
